# wrangler.toml

name = "mhtlim-static"
compatibility_date = "2023-10-30"

[site]
bucket = "./"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    # X-Frame-Options = "DENY"
